// async
export const EXHIBITION_LIST_REQUEST = 'EXHIBITION_LIST_REQUEST';
export const EXHIBITION_LIST_RECEIVE = 'EXHIBITION_LIST_RECEIVE';
export const EXHIBITION_LIST_FAILURE = 'EXHIBITION_LIST_FAILURE';
export const EXHIBITION_DELETE_REQUEST = 'EXHIBITION_DELETE_REQUEST';
export const EXHIBITION_DELETE_RECEIVE = 'EXHIBITION_DELETE_RECEIVE';
export const EXHIBITION_DELETE_FAILURE = 'EXHIBITION_DELETE_FAILURE';

