// async
export const BANNER_LIST_REQUEST = 'BANNER_LIST_REQUEST';
export const BANNER_LIST_RECEIVE = 'BANNER_LIST_RECEIVE';
export const BANNER_LIST_FAILURE = 'BANNER_LIST_FAILURE';
export const BANNER_DELETE_REQUEST = 'BANNER_DELETE_REQUEST';
export const BANNER_DELETE_RECEIVE = 'BANNER_DELETE_RECEIVE';
export const BANNER_DELETE_FAILURE = 'BANNER_DELETE_FAILURE';

