// async
export const MURAL_LIST_REQUEST = 'MURAL_LIST_REQUEST';
export const MURAL_LIST_RECEIVE = 'MURAL_LIST_RECEIVE';
export const MURAL_LIST_FAILURE = 'MURAL_LIST_FAILURE';
export const MURAL_DELETE_REQUEST = 'MURAL_DELETE_REQUEST';
export const MURAL_DELETE_RECEIVE = 'MURAL_DELETE_RECEIVE';
export const MURAL_DELETE_FAILURE = 'MURAL_DELETE_FAILURE';

