// async
export const EXHIBITION_ADD_REQUEST = 'EXHIBITION_ADD_REQUEST';
export const EXHIBITION_ADD_RECEIVE = 'EXHIBITION_ADD_RECEIVE';
export const EXHIBITION_ADD_FAILURE = 'EXHIBITION_ADD_FAILURE';

